# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e1a83fe5de420c7b528c903059ac07809c068a5396ffd5a73b1f991889750dbe9562f5988cec30b8569605654f7876c02ee54c7b905d6c8f118ac1935fc5c5

test:
  secret_key_base: 47817774fbe43e25597b24ee95071bc8f2650d67a774c48afcfa232b5adc33402d4ee4161cc7a820d066b41ed9915a1f3e5a00df5e337ac1c4ccd285f90f0caa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
